name: Create and publish the Docker image

on:
  push:
    branches: ['main']
    tags: ['*']
    paths:
      - '.github/**'
      - 'container/**'
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-kubo:
    name: 'test:kubo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: L1-node

      - name: Checkout Kubo fork
        uses: actions/checkout@v3
        with:
          repository: filecoin-saturn/kubo
          ref: refs/heads/saturn
          path: kubo

      - name: Install Kubo gateway test dependencies
        run: |
          cd $GITHUB_WORKSPACE/kubo
          make test_sharness_deps

      - name: Run Kubo gateway tests
        run: |
          export L1_NODE_REPO_PATH=$GITHUB_WORKSPACE/L1-node
          #export L1_NODE_LOG_FILE=/tmp/node.log

          cd $GITHUB_WORKSPACE/kubo/test/sharness

          for file in $(find .  -maxdepth 1 -name 't011*-gateway*.sh' -type f); do
            echo
            if [[ $file == *"t0111"* || $file == *"t0114"* ]]; then
              echo Skip $file
              continue
            fi
            echo Running $file
            bash $file
          done

      # - name: Print L1 logs
      #   if: always()
      #   run: cat /tmp/node.log

  build-and-push-image:
    needs: [test-kubo]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set orchestrator env (main)
        if: github.ref_type == 'tag'
        run: echo "SATURN_NETWORK=main" >> $GITHUB_ENV

      - name: Set orchestrator env (test)
        if: github.ref_type == 'branch'
        run: echo "SATURN_NETWORK=test" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/filecoin-saturn/l1-node:${{ env.SATURN_NETWORK }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/filecoin-saturn/l1-node:${{ env.SATURN_NETWORK }}
          cache-to: type=inline
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            RUN_NUMBER=${{ github.run_number }}
            SATURN_NETWORK=${{ env.SATURN_NETWORK }}
