name: Create and publish the Docker image

on:
  push:
    branches: ['main', 'test']
    paths:
      - 'container/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set orchestrator env (main)
        if: github.ref_name == 'main'
        run: echo "ORCHESTRATOR_URL=https://orchestrator.strn.network" >> $GITHUB_ENV

      - name: Set orchestrator env (test)
        if: github.ref_name == 'test'
        run: echo "ORCHESTRATOR_URL=https://orchestrator.saturn-test.network" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            RUN_NUMBER=${{ github.run_number }}
            ORCHESTRATOR_URL=${{ env.ORCHESTRATOR_URL }}
